package exception.trycatch;

public class ExceptionEx9 {

    public static void main(String[] args) throws Exception {

        throw new Exception(); // Exception고의 발생
    }
}
